# Generated by Django 4.2 on 2023-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded_from', models.FileField(upload_to='uploaded_files/', verbose_name='Загруженный csv-файл')),
                ('table_name', models.CharField(max_length=256, verbose_name='Имя загруженного csv-файла')),
                ('data', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'FileData',
            },
        ),
    ]
