# Generated by Django 4.2 on 2023-09-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='loaded_from',
            field=models.FileField(upload_to='uploaded_files/', verbose_name='Файл с данными'),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='table_name',
            field=models.CharField(max_length=256, verbose_name='Имя загруженного файла'),
        ),
    ]
