# Generated by Django 4.2 on 2023-09-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0002_alter_filedata_loaded_from_alter_filedata_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedata',
            name='table_name',
        ),
        migrations.AddField(
            model_name='filedata',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Имя загруженного файла'),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
