# Generated by Django 4.2 on 2023-09-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0003_remove_filedata_table_name_filedata_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedata',
            old_name='loaded_from',
            new_name='file',
        ),
    ]
