# Generated by Django 4.2 on 2023-09-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0004_rename_loaded_from_filedata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='file',
            field=models.FileField(upload_to='uploaded_files/', verbose_name='Объект файла'),
        ),
    ]
