# Generated by Django 4.2 on 2023-09-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_data', '0005_alter_filedata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='file',
            field=models.FileField(upload_to='uploaded_files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Имя файла'),
        ),
    ]
